### PR TITLE
Setup linters and react app

### PR DESCRIPTION
**Pull request by leonardodiasb**
On this PR I:

- Setup React using Create React App (CRA).
- Setup React Linters.

### CODE REVIEW

**Review by Dipeshtwis — COMMENTED** [review]
# Status: Invalid ❌

Please fix the issue mentioned below and then request for code review

## Reason

- [ ] Both CSS and JS Linters are failing. Please fix it before requesting a code review.

### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

**_Dipesh Kumar_**

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @leonardodiasb 😃, 

Well done making the linters 👏🏻
Your project is technically complete! However, there are still a few changes that need to be made to get the approval 😊

- For professional README file, please fix the MIT and issues page links 😊🙏🏻

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hi @leonardodiasb 😃, 

- Thanks for implementing the changes requested. However, the issues page is still taking me to a dead end, please fix it as well 😊🙏🏻

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leonardodiasb** [comment]
Hello @MahmoudBakr23,
Thanks for the review. But what do you mean about issues page link? Should I put the issues link(https://github.com/leonardodiasb/math-magicians/issues) of the repo inside the README?
I never put it in the README and I never saw anyone put it too.

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @leonardodiasb 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
